---
grails:
  profile: web
  codegen:
    defaultPackage: app.timali
  gorm:
    reactor:
      events: false

  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: 'app.timali.Usuario'
        authorityJoinClassName: 'app.timali.UsuarioRole'
      authority:
        className: 'app.timali.Role'

      # Desativa CSRF (Obrigatório para APIs REST stateless)
      csrf:
        active: false

      # Regras de acesso estático
      controllerAnnotations:
        staticRules:
          - {pattern: '/',               access: ['permitAll']}
          - {pattern: '/error',          access: ['permitAll']}
          - {pattern: '/api/login',      access: ['permitAll']}
          - {pattern: '/api/**',         access: ['isFullyAuthenticated()']}
          - {pattern: '/**',             access: ['permitAll']}

      # Configuração REST e JWT - ESTA É A PARTE CRÍTICA
      rest:
        login:
          active: true
          endpointUrl: '/api/login'

        token:
          storage:
            jwt:
              secret: 'timali-super-secret-key-for-jwt-2026-xyz-must-be-long-enough-to-work'
              expiration: 3600

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
  main:
    allow-bean-definition-overriding: true

hibernate:
  cache:
    queries: false
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl:
    auto: create
  show_sql: true
  format_sql: true

dataSource:
  pooled: true
  driverClassName: org.postgresql.Driver
  username: timali_user
  password: timali_password
  dbCreate: create

environments:
  development:
    dataSource:
      dbCreate: create
      url: jdbc:postgresql://localhost:5433/timali_db
      driverClassName: org.postgresql.Driver
      username: timali_user
      password: timali_password
      properties:
        hibernate:
          hbm2ddl:
            auto: create
          show_sql: true
          format_sql: true
