# Application YAML Configuration

# CORS Configuration

grails:
  cors:
    enabled: false  # Disable CORS at Grails level

spring:
  security:
    filter:
      chain:
        ignore:
          - /**   # Bypass OPTIONS requests

    rest:
      cors:
        enabled: false  # Disable CORS in Spring Security REST

    security:
      filterChain:
        staticRules:
          - antMatcher: /**
            access: permitAll  # Allow OPTIONS requests globally without authentication

# Other Configuration settings
